config/routes.rb
Organizeme::Application.routes.draw do
		resources :tasks do
			resources :priority
			resources :tags
		end

  root :to => 'home#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
 has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :title,	:priority, :presence => true
	validates_numericality_of :priority, :less_than_or_equal_to => 5
	has_many :tags

	accepts_nested_attributes_for :tags, :allow_destroy => :true,
		:reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
		@tasks = Task.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

	private

	def sort_column
		Task.column_names.include?(params[:sort]) ? params[:sort] : "priority"
	end

	def sort_direction
		%w[deasc asc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == @sort_column ? "current #{@sort_direction}" : nil
		direction = column == @sort_column && @sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1>A simple organizer for the constantly unorganized.</h1>
<h1>That is, me.</h1>
<div id="the_link">
	<%= link_to "Organize.me!", tasks_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Organize.me</title>
  <%= stylesheet_link_tag    "style", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id = "container">
	<%= yield %>
	</div>

</body>
</html>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
	<div class="field">
		<%= tag_form.text_field :name %>
	</div>
	<% unless tag_form.object.nil? || tag_form.object.new_record? %>
		<div class="field">
			<%= tag_form.label :_destroy, 'Remove:' %>
			<%= tag_form.check_box :_destroy %>
		</div>
	<% end %>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<div class = "actions">
	<%= link_to 'Show', @task %> |
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tags/index.html.erb
<table class="main_table">
	<tr>
		<th>Tags</th>
		<th>Posts tagged:</th>
    <th>Options</th>
  </tr>

<? @tags.each do |tag| %>
	<tr>
		<td class = "tag_name"><? tag.name %></td>
    <td class = "posts_tagged"><? task.title %></td>
		<td class = "options"><%# link_to 'Show', task %> 
		</td>
  </tr>
<? end %>
</table>

<br />

<table class="actions">
	<tr><td><%= link_to 'New Task', new_task_path %></td>
	<td>Edit tags</td>
	<td>Clear finished tasks</td>
	<td>Mark all finished</td>
	<td><%= link_to 'ROAR!', root_path %></td>
	</tr>
</table>

app/views/tags/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<div class = "actions">
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<div id="tag_show">
	<p class="tag">
		<b>Name:</b>
		<%= @tag.name %>
	</p>

	<p class= tagged_tasks">
	  <b>Tasks tagged by:</b>
	  <%= @task.priority %>
		</p>
	<div class="actions">
		<%= link_to 'Edit', edit_tag_path(@tag) %> |
		<%= link_to 'Back', tags_path %>
	</div>
</div>

app/views/tasks/_form.html.erb
<%= @task.tags.build %>
<%= form_for(@task) do |task_form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<table class="table_edit">
		<tr><td><div class="field">
					<b><%= task_form.label :title %></b></td>
			<td><%= task_form.text_field :title %>
			</div></td></tr>
		<tr><td><div class="field">
					<b><%= task_form.label :details %></b></td>
			<td><%= task_form.text_area :details %>
			</div></td></tr>
		<tr><td><div class="field">
					<b><%= task_form.label :priority %></b> (between 1 and 5)</td>
				<td><%= task_form.text_field :priority %>
				</div></td></tr>
		<tr><td><div class="field">
				<b><%= task_form.label :progress %></b> (in %)</td>
		    <td><%= task_form.text_field :progress %>
				</div></td></tr>
				<tr><td>Tags:</td><td><%= render :partial => 'tags/form',
					:locals => {:form => task_form} %></td></tr>
	<tr><td colspan=2><div class="actions">
				<%= task_form.submit %>
</div></td></tr></table>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<div class = "actions">
	<%= link_to 'Show', @task %> |
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/index.html.erb
<table class="main_table">
	<tr>
		<th><%= sortable "priority" %></th>
    <th><%= sortable "title" %></th>
		<th><%= sortable "details" %></th>
		<th><%= sortable "progress" %></th>
		<th>Tags</th>
    <th>Options</th>
  </tr>

<% @tasks.each do |task| %>
	<tr>
		<td class = "priority"><%= task.priority %></td>
    <td class = "title"><%= task.title %></td>
		<td class = "details"><%= task.details %></td>
		<td class = "progress"><%= task.progress %>%</td>
		<td class = "tags"><%= task.tags.map { |t| t.name }.join(", ")  %></td>
		<td class = "options"><%# link_to 'Show', task %> 
			<%= link_to 'Edit', edit_task_path(task) %><br />
    <%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<table class="actions">
	<tr><td><%= link_to 'New Task', new_task_path %></td>
	<td>Edit tags</td>
	<td>Clear finished tasks</td>
	<td>Mark all finished</td>
	<td><%= link_to 'ROAR!', root_path %></td>
	</tr>
</table>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<div class = "actions">
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div id="task_show">
	<p class="title">
		<b>Title:</b>
		<%= @task.title %>
	</p>

	<p class= "priority">
	  <b>Priority:</b>
	  <%= @task.priority %>
		</p>
	<p class= "progress">
	  <b>Progress:</b>
	  <%= @task.progress %>%
	</p>

	<p class="details">
		<b>Details:</b>
		<%= @task.details %>
		</p>
	<p class="tags">
		<b>Tags:</b>
		<%= @task.tags.map { |t| t.name }.join(", ") %>
	</p>

	<div class="actions">
		<%= link_to 'Edit', edit_task_path(@task) %> |
		<%= link_to 'Back', tasks_path %>
	</div>
</div>